title: "CS 499 Capstone ePortfolio"
description: "Computer Science Capstone ePortfolio (CS 499)"
#theme: hacker
remote_theme: pages-themes/hacker@v0.2.0

url: "https://keithpotz.github.io"
baseurl: "/CS499"  # keep empty for a root repo Pages site

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Show these pages in the header nav (Minima theme)
header_pages:
  - index.md
  - code-review.md
  - software-design.md
  - algorithms.md
  - databases.md
  - artifacts.md
